# 난수 발생과 카운팅
> ### 시드(seed)에 대한 학습 <br>
1. **필요성:** <br>
        향후 학습 및 개발시 코드와 결과를 재현하기 위한 기술 중 
       하나로 발생되는 난수를 예측할 수 있게 실행하는 하나의 기술
2. **원리 :**  <br>
        컴퓨터 프로그램에서 발생하는 무작위 수는 어떤 특정한 시적 숫자를 제시해 주면 
       컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성한다.
3. **사용 :** <br>
        seed 라는 이 값을 동일하게 맞춰서 사용하면 된다

In [1]:
import numpy as np

In [2]:
## seed
np.random.seed(0)

In [3]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [5]:
## seed
np.random.seed(0)

In [6]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [7]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])