## NumPy 유니버설 함수

1. ndrarray 내에 있는 데이터 원소별로 연산을 수행하는 함수

- 하나 이상의 스칼라값을 받아서 하나 이상의 스칼라 결과값을 반환

- 고속으로 수행할 수 있는 벡터화된 래퍼 함수

- 함수 종류<br><br>
&nbsp;&nbsp; 1. 단항 유니버설 함수 : 하나의 인자를 받아서 반환, p136<br>
&nbsp;&nbsp; 2. 이항 유니버설 함수 : 두개의 인자를 받아서 단일 배열 반환, p137
    
- ufunc

In [1]:
import numpy as np

단항 유니버셜 함수

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 각 원소의 제곱근 구하는 함수 
# 배열내에 데이터가 10(요소가 10)
# 함수 실행 직후 요소가 10가 반환
# 배열은 한개
np.sqrt(arr)  

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

이항 유니버셜 함수

In [5]:
#x,y 변수에 난수 발생해서 요소3의  정수값으로 각 1차원 배열 만들기

In [6]:
x = np.random.randint(100, 999, size=3)

In [7]:
x

array([162, 962, 113])

In [8]:
y = np.random.randint(100, 999, size=3)

In [9]:
y

array([586, 938, 513])

In [10]:
np.maximum(x, y)

array([586, 962, 513])