# NumPy 학습

1. 파이썬에서 배열을 사용하기 위한 수치 해석용 표준 패키지
- 적은 메모리로 데이터를 빠르게 처리할 수 있음
- 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용
- 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠름
- 벡터화 연산(vectorized operation)을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있음
- 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있음
- C언어의 배열처럼 연속적인 메모리 배치를 하기 때문에 모든 원소가 같은 자료형이어야 함
- 이러한 제약사항이 있는 대신 원소에 대한 접근과 반복문 실행이 빨라짐
- ndarray 는 N-dimensional Array의 약자로 1차원, 2차원,  3차원 배열 등의 다차원 배열 자료 구조를 지원
- **2차원 배열은 행렬(matrix)** 이라고 하는데 행렬에서는 가로줄을 행 *(row)이라고 하고 세로줄을 *열(column)이라 함
- 다차원 배열 : 리스트의 리스트(list of list)를 이용하면 2차원 배열을 생성할 수 있음. 
- 안쪽 리스트의 길이는 행렬의 열의 수 즉, 가로 크기가 되고 바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기를 의미
- url<br>
http://www.numpy.org/<br>
https://docs.scipy.org/doc/numpy-1.15.0/reference/index.html#reference


### NumPy 패키지 import

> NumPy는 np라는 이름으로 임포트하는 것이 관례

In [2]:
!pip show numpy

Name: numpy
Version: 1.15.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\playdata\anaconda3\lib\site-packages
Requires: 
Required-by: tables, seaborn, PyWavelets, pytest-doctestplus, pytest-arraydiff, patsy, pandas, odo, numexpr, numba, mkl-random, mkl-fft, matplotlib, h5py, datashape, Bottleneck, bokeh, bkcharts, astropy


In [3]:
import numpy as np

### Numpy 필요성 인지를 위한 간략 코드
- 반복문 실행 시간 비교하기

- %time 단일 문장의 실행시간 측정
- %timeit 단일 문장을 반복실행해 더 정확하게 실행시간을 측정

In [3]:
#numpy로 데이터 구성
numpyArray = np.arange(10000000)
plist = list( range(10000000) )

In [4]:
%time for _ in range(10): numpyArray = numpyArray * 2  # 391 ms 밀리초 
%time for _ in range(10): plist = [x * 2 for x in plist]

Wall time: 391 ms
Wall time: 16.6 s


### NumPy 모듈을 사용한 1차원 배열 만들기

- array 함수에 리스트를 넣으면 배열로 변환

In [5]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(data)
type(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [6]:
# 정수 배열
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(data)


[0 1 2 3 4 5 6 7 8 9]


In [8]:
type(data)

numpy.ndarray

In [13]:
# 몇차원 배열 여부 확인
data.ndim


1

In [11]:
data.shape

(10,)

In [15]:
#dtype을 이용한 실수 배열 타입
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype = 'float')
print(data)
print(type(data))


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


In [16]:
type(data)

numpy.ndarray

### NumPy 모듈을 사용한  2차원 배열 만들기

In [18]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
data.ndim # 2차원 배열 확인

2

In [23]:
data.shape # (2, 3) 2행 3열

(2, 3)

In [31]:
data[0]


array([4, 5, 6])

In [33]:
data[1]

array([4, 5, 6])

In [36]:
# 2행 3열 값을 60으로 바꾸기
data[1][2] = 60
print(data)

[[ 1  2  3]
 [ 4  5 60]]


In [42]:
len(data) # 2 개의 행

2

In [43]:
len(data[0]) # 3개의 열

3

In [41]:
# 오류 len(data[0][0])

TypeError: object of type 'numpy.int32' has no len()

### NumPy 모듈을 사용한  3차원 배열 만들기

리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있음<br>
크기를 나타낼 때는 가장 **바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로** 표시<br>
예를 들어 2 x 3 x 4 배열은 다음과 같이 구성

In [56]:
# 2 x 3 x 4
data = np.array([[[1,2,3,4],[5,6,7,8],[9,8,7,6]],
                [[5,4,3,2],[1,2,3,4],[5,6,7,8]]])
data

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 8, 7, 6]],

       [[5, 4, 3, 2],
        [1, 2, 3, 4],
        [5, 6, 7, 8]]])

### 3차원 배열의 행, 열, 깊이

In [50]:
data.ndim

3

In [54]:
data.shape

(2, 3, 4)

In [67]:
print(len(data[1][0]))
print(data[1][0])


4
[5 4 3 2]


In [70]:
data[1][1][3] = 47
data

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9,  8,  7,  6]],

       [[ 5,  4,  3,  2],
        [ 1,  2,  3, 47],
        [ 5,  6,  7,  8]]])

In [71]:
data[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

### NumPy 함수를 사용하여 배열 생성하기

1. 규모가 큰 배열의 경우에는 NumPy에 내장된 루틴을 사용해서 처음부터 배열을 생성하는 것이 효율적
- 주요 함수<br>
a. zeros, ones <br>
b. zeros_like, ones_like<br>
c. empty<br>
d. arange : 특정한 규칙에 따라 증가하는 수열 만들기<br>
e. linspace, logspace : 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할<br>
f. rand, randn<br>

In [76]:
# 0 값으로 정수 배열 만들기, int 형 10개 
data = np.zeros(10, dtype=int)
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
data.shape

(10,)

In [82]:
# 1값으로 10개의 데이터를 보유한 numpy 배열 만들고 출력
# dtype 생략시 1.0의 실수 출력
data = np.ones(10, dtype=int)
data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [88]:
# 다차원 배열 , 2행 3열
data = np.zeros((2, 3), dtype=int)
data

array([[0, 0, 0],
       [0, 0, 0]])

In [90]:
data[1][2] = 100
data 

array([[  0,   0,   0],
       [  0,   0, 100]])

In [95]:
# ? 2행 3열의 열의 값 3이 출력되게 하세요
len(data[1])

3

In [97]:
data = np.full((3,5), 5) # 3행 5열을 생성, 5로 채움
data

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [99]:
# 0~10 까지의 범위 내에서 2씩 증가되는 배열 생성(수열 처럼 동작 가능)
data = np.arange(0, 10, 2)
data

array([0, 2, 4, 6, 8])

In [107]:
# (0.1 ~ 1) 까지 10 개의 값을 가지는 배열 생성
np.linspace(0, 5, 2)

array([0., 5.])

In [109]:
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [111]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [120]:
# 난수 발생 ( 0~1 사이 )
data = np.random.random((3,3))
data

array([[0.43516935, 0.502977  , 0.57009857],
       [0.56605464, 0.47343525, 0.94383094],
       [0.02610441, 0.5775852 , 0.57447205]])

In [125]:
# random.randint로 정수범위 0~10 까지 3행3열 배열 생성
np.random.randint(0,10,(3,3))

array([[9, 4, 1],
       [5, 9, 2],
       [9, 3, 4]])

- np.eye() : 단위 행렬 구성 
- [API doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)

In [94]:
# 3x3 단위 행렬 만들기
np.eye(3 , dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## NumPy 배열의 기초

### 배열 속성 지정

> 각 배열이 보유하고 있는 속성들

1. ndim : 차원의 개수
- shape : 각 차원의 크기
- size : 전체 배열 크기 <br>


2. randint(max-1 , size(n,m)) <br>
   = randint(min , max-1 , (n,m)) 

In [ ]:
# 동일한 난수 배열이 생성되도록 시드값 설정
np.random.seed(0)

정수 범위내의 난수 발생해서 1차원~3차원 배열 생성해 보기

In [127]:
x1 = np.random.randint(10, size=6) # 1차원 배열
x2 = np.random.randint(0 , 10, (3, 4)) # 2차원 배열
x3 = np.random.randint(10, size=(3, 4, 5))# 3차원 배열

In [177]:
x1 = np.random.randint(10, size=6)
x1

array([5, 0, 7, 6, 1, 8])

In [197]:
x2 = np.random.randint(0 , 10, (3, 4)) 
x2

array([[9, 2, 8, 6],
       [5, 9, 3, 2],
       [4, 6, 8, 4]])

In [203]:
x3 = np.random.randint(10, size=(3, 4, 5))
x3

array([[[9, 3, 1, 1, 5],
        [5, 4, 2, 7, 9],
        [1, 9, 9, 8, 1],
        [8, 0, 6, 8, 7]],

       [[1, 7, 8, 0, 4],
        [3, 0, 6, 0, 2],
        [5, 7, 9, 5, 9],
        [2, 1, 7, 3, 5]],

       [[6, 5, 8, 2, 7],
        [9, 0, 0, 0, 5],
        [5, 9, 8, 5, 2],
        [9, 9, 8, 7, 7]]])

### 배열 indexing : 단일 요소 접근하기

In [206]:
x1 = np.random.randint(10, size = 6) # 0~9 까지 정수형 난수 발생
x1

array([5, 9, 7, 5, 8, 1])

### 배열의 색인과  슬라이싱 
> x[start : stop : step] <br>
하위 배열에 접근하기

In [208]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
type(x)

numpy.ndarray

In [210]:
x[:5]

array([0, 1, 2, 3, 4])

In [228]:
x[::3] # 3씩 점프? or 3씩 더하기?
# ::3칸씩 걸러내는 구성

array([0, 3, 6, 9])

In [231]:
x = np.arange(10)

In [230]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [248]:
# ? [5,3,1]
x[5::-2]

array([[7, 8, 9],
       [1, 2, 3]])

In [254]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [255]:
x.shape

(3, 3)

In [252]:
data1 = x[:2]
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [257]:
data2 = x[:2, 1:]
data2

array([[2, 3],
       [5, 6]])

In [260]:
data3 = x[2:2]
data3

array([], shape=(0, 3), dtype=int32)

In [262]:
data4 = x[:, 1:2]
data4

array([[2],
       [5],
       [8]])

### 데이터 복사 이해하기

> NumPy는 대용량 데이터 처리를 염두해 두고 설계되었기 때문에 NumPy가 데이터 복사를 남발할 경우 성능과 메모리 문제 발생 가능성이 있음
<br>
별도의 복사된 데이터를 활용하고자 할 경우 copy() 함수 사용

copy() 함수를 사용하지 않은 경우

In [264]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [266]:
# index시작:끝
x[3:8]

array([3, 4, 5, 6, 7])

In [271]:
# array([0,1,2,3,4,30,30,30,8,9])
x = np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [273]:
x[5:8] = 30
x

array([ 0,  1,  2,  3,  4, 30, 30, 30,  8,  9])

In [274]:
y = x[5:8]
y

array([30, 30, 30])

In [275]:
y[0] = 100
y

array([100,  30,  30])

In [277]:
x # y를 바꾸었는데도 x까지 바껴짐, 조심해야함

array([  0,   1,   2,   3,   4, 100,  30,  30,   8,   9])

copy() 함수를 사용한 경우

In [278]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [282]:
y = x[5:8].copy()
y[0] = 100
y

array([100,   6,   7])

In [284]:
x # copy()로 x의 주소번지로 복사, y로 복사함, 원본 데이터를 참조하지 않음

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> 다차원 하위 배열

In [286]:
x2 = np.random.randint(10, size=(3,4)) # 2차원 배열
x2

array([[2, 5, 7, 6],
       [8, 5, 1, 9],
       [0, 4, 3, 5]])

In [289]:
x2.ndim

2

In [290]:
x2[0].ndim

1

In [292]:
x2.shape

(3, 4)

In [294]:
x2[0].shape

(4,)

In [302]:
x2[0][:] # 1행 4열

array([2, 5, 7, 6])

In [301]:
x2[:2,:] # ~2행, ~4열까지

array([[2, 5, 7, 6],
       [8, 5, 1, 9]])

In [300]:
x2[:3, :3] # 3행 3열까지만 출력

array([[2, 5, 7],
       [8, 5, 1],
       [0, 4, 3]])

> ## 배열의 재 구조화
 - 매우 중요!!! 

In [310]:
# reshape() 메소드
data = np.arange(1, 10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [311]:
# 1차원 배열을 3행 3열로 만들겠다. 구조를 바꾸겠다. reshape
x = data.reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [313]:
x.shape

(3, 3)

In [315]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [316]:
data.ndim

1

In [318]:
data.shape # (3,) 처럼 단일행은 열을 무시하고 출력

(3,)

In [322]:
x = data.reshape(3,1) # 열벡터
x

array([[1],
       [2],
       [3]])

In [323]:
x.shape

(3, 1)

> ### 배열 연결 및 분할
- 여러 배열을  하나로 결합 또는 하나의 배열을 여러 개의 배열로 분할하기
- np.concatenate() numpy의 배열과 python의 list 결합도 가능
- np.vstack
- np.hstack 
    루틴을 이용해 두 배열 결합 및 연결

### 1차원 배열간의 결합

In [338]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = [5,6,7]

In [339]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [340]:
print(type(x))
print(type(y))
print(type(z))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'list'>


In [344]:
data1 = np.concatenate([x,y,z])
data1

array([1, 2, 3, 3, 2, 1, 5, 6, 7])

In [345]:
data2 = np.vstack([x,y,z])
data2

array([[1, 2, 3],
       [3, 2, 1],
       [5, 6, 7]])

In [348]:
data3 = np.hstack([x,y,z])
data3

array([1, 2, 3, 3, 2, 1, 5, 6, 7])

### 2차원 배열간의 결합

In [360]:
data = np.array([ [1,2,3],[5,6,7] ])
data

array([[1, 2, 3],
       [5, 6, 7]])

In [361]:
data.ndim

2

In [362]:
data.shape

(2, 3)

In [363]:
# 새로운 numpy 배열 생성 (3차원)
data2 = np.array([data, data]) 
data2

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [364]:
data2.shape

(2, 2, 3)

In [365]:
data2[0]

array([[1, 2, 3],
       [5, 6, 7]])

In [374]:
 # axis = 1 열을 의미, 열대로 concat
data3 = np.concatenate([data, data] ,axis = 1)
data3

array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])

In [375]:
data3.shape

(2, 6)

In [376]:
# 이미 존재하는 row 에 결합해서 추가
data4 = np.concatenate([data, data] , axis = 0)
data4

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [378]:
data4.shape

(4, 3)

In [380]:
data # 원본 데이터는 바뀌지 않음

array([[1, 2, 3],
       [5, 6, 7]])

> ## 혼합된 차원의 배열
- 행의 수나 열의 수가 같은 두개 이상의 배열을 연결하여 더 큰 배열 생성하는  명령어
- np.vstack : 수직 스택, vertical stack 
              = 컬럼 갯수는 맞아야함 <br>
- np.hstack : 수평 스택, horizontal stack 
              = 하나의 컬럼에 속해있는 row 개수는 동일해야함
- dstack : 제 3의 축, 즉 행이나 열이 아닌 깊이 방향으로 배열을 결합, 가장 안쪽의 원소 차원이 증가
- stack : 사용자가 지정한 차원(축)으로 연결
- r_ : hstack과 함께 배열을 좌우로 연결
- c_ : 배열의 차원을 증가시킨 후 좌우로 연결, 가령 1차원 배열을 연결하면 2차원 배열이 됨
- tile : 동일한 배열을 반복하여 연결

In [381]:
x = np.array([1,2,3])
data = np.array([[5,6,7], [8,9,10]])

In [385]:
print(x)
print(data)
print("x : " , x.ndim," ",x.shape)
print("data : " , data.ndim," ",data.shape)

[1 2 3]
[[ 5  6  7]
 [ 8  9 10]]
x :  1   (3,)
data :  2   (2, 3)


In [387]:
np.vstack([x, data]) # 수직 스택, 수직으로 쌓임

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [399]:
np.hstack([x, data]) # 수평 스택, 수평으로 쌓임 but, data가 2차원이라서 연결 안됨( 행의 수가 같아야함 )

ValueError: all the input arrays must have same number of dimensions

In [400]:
np.hstack([x,x])

array([1, 2, 3, 1, 2, 3])

In [401]:
y = np.array([ [100] , [100] ])
y

array([[100],
       [100]])

In [402]:
np.hstack([x,y])

ValueError: all the input arrays must have same number of dimensions

In [405]:
np.hstack([y, data]) # y와 data는 행의 수가 같음

array([[100,   5,   6,   7],
       [100,   8,   9,  10]])

In [414]:
np.vstack([x.y]) # row에 속해있는 갯수가 서로 다름

AttributeError: 'numpy.ndarray' object has no attribute 'y'

In [421]:
zz = np.hstack([data,[[x],[y]]]) # ? 
zz

array([[5, 6, 7, array([1, 2, 3])],
       [8, 9, 10, array([[100],
       [100]])]], dtype=object)

In [423]:
zz.shape # ? 

(2, 4)

> ### 배열 분할하기
- np.split, np.hsplit, np.vsplit

In [424]:
x = [1,2,3,100,100,3,2,1]

In [429]:
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [100 100] [3 2 1]


In [464]:
'''
1. arange
2. reshape 로 4행 4열 0~15
3. up, down = split() 
    up 출력시 -> [[0,1,2,3]]
'''
x  = np.arange(0,16)
print(x)
print(x.ndim, x.shape)
rex = x.reshape(4,4)
print(rex)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1 (16,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [472]:
up, down = np.split(rex, [1])
print(up)
print(down)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [470]:
up, down = np.vsplit(rex, [1])
print(up)

[[0 1 2 3]]


In [474]:
up, down = np.hsplit(rex, [1])
print(up)
print(down)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [478]:
# 0으로 채워진 3,4
data = np.zeros((3,4),dtype=int)
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [483]:
x = np.tile(data, 3)
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [484]:
x.shape

(3, 12)

>  ## <font color=red>  전치 연산 </font>
- 2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업
- 이는 배열의 T 속성으로 구할 수 있음
- 메서드가 아닌 속성

In [486]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [488]:
data.T # 행과 열을 바꿈

array([[1, 4],
       [2, 5],
       [3, 6]])

In [489]:
data.T.T

array([[1, 2, 3],
       [4, 5, 6]])

> ### 다차원 배열을 1차원으로 변환하기
1. flatten or  ravel 함수 사용

In [491]:
data = np.arange(1,10,1)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [497]:
data.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [500]:
data.flatten() # 1차원 배열로 만듬

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 벡터화 연산(vectorized operation)

1.  배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리
- 일반 for 반복문 없이 한번의 연산으로 처리 가능
- 실행 속도도 빠름
- 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [5]:
# 일반 python 배열
data = [0, 1, 2, 3, 4, 5]

In [6]:
# for 반복문을 사용힌 경우
result = []
for no in data:
    result.append(no*2)
result

[0, 2, 4, 6, 8, 10]

> NumPy는 벡터화 연산 사용시 빠른 연산 가능

In [11]:
import numpy as np

In [7]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5])

In [9]:
x * 2

array([ 0,  2,  4,  6,  8, 10])

In [10]:
x.size

6

> 일반 리스트 객체에 정수를 곱하면 객체의 크기가 정수배 만큼으로 증가

In [12]:
data = [1,2,3]
data * 2

[1, 2, 3, 1, 2, 3]

> 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [14]:
x = np.array([1,2,3])
y = np.array([10,20,30])

In [16]:
x+y

array([11, 22, 33])

In [18]:
y-x

array([ 9, 18, 27])

In [20]:
x*y

array([10, 40, 90])

In [22]:
y/x

array([10., 10., 10.])

In [23]:
y[0]

10

In [25]:
y[0]=1
y

array([ 1, 20, 30])

In [26]:
x==y

array([ True, False, False])

In [27]:
y>10

array([False,  True,  True])

In [28]:
x

array([1, 2, 3])

In [29]:
y

array([ 1, 20, 30])

In [30]:
z = np.array([0, 20, 0.1])

In [31]:
z2 = np.arange(0, 10, 0.1)

In [32]:
z

array([ 0. , 20. ,  0.1])

In [33]:
z2

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [34]:
z.size, z2.size

(3, 100)

<!--NAVIGATION-->
<[step02 NumPy 함수 학습](step02_NumpyFun.ipynb) >